blog/blogadmin/urls.py
from django.conf.urls import url,include
from blogadmin.views import adminIndex,NewAccounts


urlpatterns = [
	url(r'^index/',adminIndex),
	url(r'^users/',NewAccounts,name="NewAccounts"),
]

blog/blogauth/urls.py
# encoding=utf8
from django.conf.urls import url,include
from django.contrib.auth.views import login,logout,password_change_done
from blogauth.views import userRegister,password_change

urlpatterns = [
    url(r'^login/$', login,{'template_name': 'registration/login.html'},name='login'),
    url(r'^logout/$', logout,{'template_name': 'registration/login.html'},name='logout'),
    url(r'^password_change/$', password_change,{'template_name': 'registration/password_change.html','post_change_redirect': '/accounts/login/'}, name='password_change'),  ##
    #不加{'post_change_redirect': 'done/'}会报NoReverseMatch Error（reverse(password_change_done)),原因未知
    url(r'^password_change/done/$', password_change_done, name='password_change_done'),
	url(r'^register/$',userRegister,name="userRegister"),
]

blog/blogdjango/urls.py
from django.conf.urls import url,include
from blogdjango import views
from django.contrib.auth.views import login
urlpatterns = [
	url(r'^index/$',views.selfIndex,name="selfIndex"),
	url(r'^test/$',views.test),
	url(r'^comment/$',views.Comment),
	url(r'^user/(?P<username>[a-zA-Z0-9]+)/$',views.userIndex),
	url(r'^user/(?P<username>[a-zA-Z0-9]+)/permission/',views.askPermission),
	url(r'^article/$',views.addNewActicle,name="addNewActicle"),
	url(r'^shortArticle/$',views.shortArticle,name="shortArticle"),
	url(r'^permission/$',views.processPermission,name="processPermission"),
	url(r'^userProfile/$',views.userProfile,name="userProfile"),
	url(r'^photo/$',views.photoView,name="photoView"),
	url(r'^uploadHeadPhoto/$',views.uploadHeadPhoto,name="uploadHeadPhoto"),
	url(r'^uploadArticlePhoto/$',views.uploadArticlePhoto,name="uploadArticlePhoto"),
]

blog/urls.py
from django.conf.urls import url,include



urlpatterns = [
	url(r'^accounts/',include("blogdjango.auth.urls",namespace="blogauth")),
	url(r'^blog/',include("blogdjango.blog.urls",namespace="blogdjango")),
	url(r'^admin/',include("blogdjango.admin.urls",namespace="blogadmin")),
]

blogdjango/models.py
# encoding=utf8
from django.db import models
from django.contrib.auth.models import User
import json 

class UserDetail(models.Model):
	user = models.OneToOneField(User)
	username = models.CharField(max_length=150,unique=True)
	nickname = models.CharField(max_length=200,default="",verbose_name=u"昵称")
	create_time = models.DateTimeField(auto_now_add=True,verbose_name=u"创建时间")
	access_confirm = models.BooleanField(default=True,verbose_name=u"访问权限控制")
	friends = models.ManyToManyField("self",through="Friends",symmetrical=False,related_name="Permission")
	contact_user = models.ManyToManyField("self",through="Message",symmetrical=False,related_name="Contact")  ###对称关系的话，through表会怎么表示
	signature = models.CharField(max_length=400,default="",verbose_name=u"个性签名")
	head_photo = models.ImageField(upload_to="face/%Y/%m/%d",null=True)
	blog_title = models.CharField(max_length=200,default="",verbose_name=u"blog名称")
	
	def __unicode__(self):
		return self.user.username  
	def getheadphotourl(self):
		try:
			return "/" + self.head_photo.url
		except ValueError:
			return "/face/default.jpg"

	class Meta:
		db_table = "user_detail"
		verbose_name = "用户详细数据"
		ordering = ["create_time"]



class Friends(models.Model):
	blog_priority = models.BooleanField(default=False,verbose_name="权限")
	ask_from_user = models.ForeignKey(UserDetail,related_name="asking_user")
	asked_user = models.ForeignKey(UserDetail,related_name="asked_user")
	ask_time = models.DateTimeField(auto_now_add=True,verbose_name=u"请求好友时间")
	need_confirm = models.BooleanField(default=True,verbose_name=u"需要审核")


	class Meta:
		db_table = "blog_friends"
		verbose_name = "博客权限"
		ordering = ["ask_time"]
		

class BlogText(models.Model):
	id = models.AutoField(primary_key=True)
	userDetail = models.ForeignKey(UserDetail)
	article_tags = models.CharField(max_length=400,default="",verbose_name=u"blogText tag")
	create_time = models.DateTimeField(auto_now_add=True,verbose_name=u"文档创建日期")
	context = models.TextField(verbose_name=u"blogText内容")
	blog_text_title = models.CharField(max_length=400,default="",verbose_name=u"blogText名称")
	is_publish = models.BooleanField(default=False,verbose_name=u"是否可以展示")

	def __unicode__(self):
		return self.blog_text_title  
	class Meta:
		db_table = "blog_text"
		verbose_name = "博客文档"
		ordering = ["-create_time"]

	def gettags(self):
		return self.article_tags.split(",")
		
class ShortArticle(models.Model):
	id = models.AutoField(primary_key=True)
	userDetail = models.ForeignKey(UserDetail)
	create_time = models.DateTimeField(auto_now_add=True,verbose_name=u"文档创建日期")
	context = models.TextField(verbose_name=u"内容")
	short_text_title = models.CharField(max_length=400,default="",verbose_name=u"名称")
	def __unicode__(self):
		return self.short_text_title  
	class Meta:
		db_table = "short_article"
		verbose_name = "短博文"
		ordering = ["-create_time"]
		
class Comment(models.Model):
	id = models.AutoField(primary_key=True)
	blogtext = models.ForeignKey(BlogText)
	parent_comment = models.ForeignKey("self",blank=True,null=True,related_name="children_comments")
	context = models.TextField()
	comment_user = models.ForeignKey(UserDetail,blank=True,null=True,on_delete=models.SET_NULL,related_name="comment_from")
	comment_to_user = models.ForeignKey(UserDetail,blank=True,null=True,on_delete=models.SET_NULL,related_name="comment_to")
	comment_time = models.DateTimeField(auto_now_add=True,verbose_name=u"评论时间")
	
	class Meta:
		db_table = "blog_comment"
		verbose_name = "博客评论"
		ordering = ["comment_time"]
		
class ShortComment(models.Model):
	id = models.AutoField(primary_key=True)
	shortarticle = models.ForeignKey(ShortArticle)
	parent_comment = models.ForeignKey("self",blank=True,null=True,related_name="children_comments")
	context = models.TextField()
	comment_user = models.ForeignKey(UserDetail,blank=True,null=True,on_delete=models.SET_NULL,related_name="short_comment_from")
	comment_to_user = models.ForeignKey(UserDetail,blank=True,null=True,on_delete=models.SET_NULL,related_name="short_comment_to")
	comment_time = models.DateTimeField(auto_now_add=True,verbose_name=u"评论时间")
	

	class Meta:
		db_table = "short_comment"
		verbose_name = "短博文评论"
		ordering = ["comment_time"]
		
class Message(models.Model):
	message = models.CharField(max_length=200,default="",verbose_name=u"聊天消息")
	contact_time = models.DateTimeField(auto_now_add=True,verbose_name=u"聊天时间")
	from_user = models.ForeignKey(UserDetail,related_name="sended_message")
	to_user = models.ForeignKey(UserDetail,related_name="recived_message")
	is_read = models.BooleanField(default=False,verbose_name=u"是否已读")
	
	class Meta:
		db_table = "blog_message"
		verbose_name = "聊天记录"
		ordering = ["-contact_time"]

class BlogPhoto(models.Model):
	id = models.AutoField(primary_key=True)
	userDetail = models.ForeignKey(UserDetail)
	upload_time = models.DateTimeField(auto_now_add=True,verbose_name=u"照片上传时间")
	photo = models.ImageField(upload_to="userphoto/%Y/%m/%d")

	def getphotourl(self):
		return "/" + self.photo.url
	class Meta:
		db_table = "blog_photo"
		verbose_name = "照片"
		ordering = ["-upload_time"]


		

blog/blogadmin/views.py
from django.shortcuts import render
from blogauth.decorators import account_admin_required
from django.template.response import TemplateResponse
from blogadmin.adminAction import adminAction
from django.http import HttpResponse
import json
# Create your views here.

@account_admin_required()
def adminIndex(request):
	username = request.user.username.split('@')[0]
	return TemplateResponse(request,"admin/base.html",{})
	
@account_admin_required()
def NewAccounts(request):
	mAdminAction = adminAction()
	if request.method == 'POST':
		context = mAdminAction.processConfirmAsk(request.POST)
		print context
		return HttpResponse(json.dumps(context),content_type="application/json")
	else:
		context = mAdminAction.queryNeedConfirmAccounts()
		return TemplateResponse(request,"admin/usermanage.html",context)

blog/blogdjango/views.py
# encoding=utf8
from django.shortcuts import render
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from blogdjango.auth.decorators import account_active_required
from blogdjango.models import UserDetail
from blogdjango.blogAction import BlogAction
from django.views.decorators.csrf import csrf_protect
from django.template.response import TemplateResponse
from django.core.exceptions import PermissionDenied
import json

# Create your views here.



@account_active_required()
def selfIndex(request):
	mblogAction = BlogAction(request.user)
	context = mblogAction.queryIndexData()
	return TemplateResponse(request,"blog/index.html",context)

@account_active_required()
def userIndex(request,username):
	mblogAction = BlogAction(request.user)
	context = mblogAction.queryIndexData(username)
	if context.has_key("denied"):
		return TemplateResponse(request,context["denied"],context)
	return TemplateResponse(request,"blog/index.html",context)

@csrf_protect
@account_active_required()
def Comment(request):
	mblogAction = BlogAction(request.user)
	if request.method == 'GET':
		context = mblogAction.queryActicleComment(request.GET)
	else:
		context = mblogAction.addNewComment(request.POST)
	if context.has_key("denied"):
		return TemplateResponse(request,context["denied"],context)
	return HttpResponse(json.dumps(context),content_type="application/json",status = context["code"])

@account_active_required()	
def askPermission(request,username):
	mblogAction = BlogAction(request.user)
	context = mblogAction.askBlogPermission(username)
	return HttpResponse(json.dumps(context),content_type="application/json",status = context["code"])

@csrf_protect
@account_active_required()
def processPermission(request):
	mblogAction = BlogAction(request.user)
	if request.method == 'GET':
		context = mblogAction.queryAskedPermission()
	else:
		context = mblogAction.processAskedPermission(request.POST)
		return HttpResponse(json.dumps(context),content_type="application/json",status = context["code"])
	return TemplateResponse(request,"blog/Permission.html",context,status = context["code"])

@csrf_protect
@account_active_required()
def addNewActicle(request):
	mblogAction = BlogAction(request.user)
	if request.method == 'POST':
		context = mblogAction.updateOrCreateArticle(request.POST)
		return HttpResponse(json.dumps(context),content_type="application/json",status = context["code"])
	else:
		context = mblogAction.queryArticle(tag=request.GET.get("tag-search",""))
		return TemplateResponse(request,"blog/ArticleEditor.html",context,status = context["code"])
		
@account_active_required()
def shortArticle(request):
	mblogAction = BlogAction(request.user)
	if request.method == 'POST':
		context = mblogAction.addNewShortArticle(request.POST)
		return HttpResponse(json.dumps(context),content_type="application/json",status = context["code"])
	else:
		context = mblogAction.queryShortArticle()
		return TemplateResponse(request,"blog/shortArticleEditor.html",context,status = context["code"])
		
def test(request):
	return TemplateResponse(request,"blog/test.html")

@account_active_required()
def userProfile(request):
	return TemplateResponse(request,"blog/userProfile.html",{})

@csrf_protect
@account_active_required()
def uploadHeadPhoto(request):
	if request.method == 'POST':
		mblogAction = BlogAction(request.user)
		context = mblogAction.uploadHeadPhoto(request.POST)
	else:
		context["code"] = 405
	return HttpResponse(json.dumps(context),content_type="application/json",status = context["code"])

@csrf_protect
@account_active_required()	
def photoView(request):
	mblogAction = BlogAction(request.user)
	if request.method == 'POST':
		context = mblogAction.uploadPhoto(request)
		return HttpResponse(json.dumps(context),content_type="application/json",status = context["code"])
	else:
		context = mblogAction.requeryPhoto()
	return TemplateResponse(request,"blog/photo.html",context,status = context["code"])


@csrf_protect
@account_active_required()
def uploadArticlePhoto(request):
	if request.method == 'POST':
		mblogAction = BlogAction(request.user)
		context = mblogAction.uploadArticlePhoto(request)
	else:
		context["code"] = 405
	return HttpResponse(json.dumps(context),content_type="application/json",status = context["code"]) 

blogdjango/admin/views.py
from django.shortcuts import render
from blogdjango.auth.decorators import account_admin_required
from django.template.response import TemplateResponse
from blogdjango.admin.adminAction import adminAction
from django.http import HttpResponse
import json
# Create your views here.
 
@account_admin_required()
def adminIndex(request):
	username = request.user.username.split('@')[0]
	return TemplateResponse(request,"admin/base.html",{})
	
@account_admin_required()
def NewAccounts(request):
	mAdminAction = adminAction()
	if request.method == 'POST':
		context = mAdminAction.processConfirmAsk(request.POST)
		return HttpResponse(json.dumps(context),content_type="application/json")
	else:
		context = mAdminAction.queryNeedConfirmAccounts()
		return TemplateResponse(request,"admin/usermanage.html",context)

blog/blogdjango/templates/blog/base_nemu.html
{% extends 'blog/base.html' %}
{% block leftmenu %}
    <nav class="navbar-default navbar-static-side" role="navigation">
        <div class="sidebar-collapse">
            <ul class="nav metismenu" id="side-menu">
                <li class="nav-header">
                      <div class="logo-element">
                         IN+
                       </div>
                 </li>
                 {% block menulist %}
                    <li class="active">
                        <a href="#"><i class="fa fa-home"></i> <span class="nav-label">首页</span> <span class="fa arrow"></span></a>
                    </li>
                    <li>
                        <a href="#"><i class="fa fa-file-text-o"></i> <span class="nav-label">博客文章</span> <span class="fa arrow"></span></a>
                        <ul class="nav nav-second-level collapse">
                        {% for acrticletype in acrticletypes %}
                        <li><a href="#">{{acrticletype.typename}}</a></li>
                        {% endfor %}
                        </ul>
                    </li>
                    <li>
                        <a href="#"><i class="fa fa-cog"></i> <span class="nav-label">博客设置</span><span class="fa arrow"></span></a>
                        <ul class="nav nav-second-level collapse">
                            <li><a href="#">权限管理</a></li>
                            <li><a href="#">待用</a></li>
                        </ul>
                    </li>
                 {% endblock %}
              </ul>
            </div>
        </nav>

        <div id="page-wrapper" class="gray-bg dashbard-1">
{% endblock %}
{% block navhead %}
        <div class="navbar-header">
            <a class="navbar-minimalize minimalize-styl-2 btn btn-primary " href="#"><i class="fa fa-bars"></i> </a>
        </div>
            <ul class="nav navbar-top-links navbar-right">
                <li>
                    <span class="m-r-sm text-muted welcome-message">欢迎您，{{user.username}},</span>
                </li>

                <li>
                    <a href="{% url 'blogauth:logout' %}">
                        <i class="fa fa-sign-out"></i> Log out
                    </a>
                </li>
                <li>
                    <a class="right-sidebar-toggle">
                        <i class="fa fa-tasks"></i>
                    </a>
                </li>
            </ul>
{% endblock %}
{% block chatbox %}
       <div class="small-chat-box fadeInRight animated">

            <div class="heading" draggable="true">
                <small id="chat-timer" class="chat-date pull-right">
                    02.19.2015
                </small>
                聊天工具
            </div>
            
            <div class="content">
             {% comment %}
                {% block chatmessage %}

                {% for message in messages %}
                    {% if message.from_user == user.username %}
                    <div class="right">
                             <div class="author-name">
                               {{ message.from_user }}
                              <small class="chat-date">
                                 {{ message.datetime }}
                               </small>
                             </div>
                       <div class="chat-message">
                                {{ message.content }}
                       </div>
                   </div>
                   {% else %}
                    <div class="left">
                             <div class="author-name">
                               {{ message.from_user }}
                              <small class="chat-date">
                                 {{ message.datetime }}
                               </small>
                             </div>
                       <div class="chat-message">
                                {{ message.content }}
                       </div>
                   </div>
                   {% endif %}
                {% endfor %}
                {% endblock %}
            {% endcomment %}
            </div>
            
            <div class="form-chat">
                <div class="input-group input-group-sm"><input type="text" class="form-control"> <span class="input-group-btn"> <button
                        class="btn btn-primary" type="button">Send
                </button> </span></div>
            </div>

        </div>
        <div id="small-chat">

            <span class="badge badge-warning pull-right">5</span>
            <a class="open-small-chat">
                <i class="fa fa-comments"></i>

            </a>
        </div>
{% endblock %}
{% block rightsidebar %}
        <div id="right-sidebar">
            <div class="sidebar-container">

                <ul class="nav nav-tabs navs-3">

                    <li class="active"><a data-toggle="tab" href="#tab-1">
                        聊天消息
                    </a></li>
                    <li><a data-toggle="tab" href="#tab-2">
                        评论
                    </a></li>
                    <li class=""><a data-toggle="tab" href="#tab-3">
                        <i class="fa fa-gear"></i>
                    </a></li>
                </ul>

                <div class="tab-content">


                    <div id="tab-1" class="tab-pane active">

                        <div class="sidebar-title">
                            <h3> <i class="fa fa-comments-o"></i> Latest Notes</h3>
                            <small><i class="fa fa-tim"></i> You have 10 new message.</small>
                        </div>

                        <div>

                            <div class="sidebar-message">
                                <a href="#">
                                    <div class="pull-left text-center">
                                        <img alt="image" class="img-circle message-avatar" src="img/a1.jpg">

                                        <div class="m-t-xs">
                                            <i class="fa fa-star text-warning"></i>
                                            <i class="fa fa-star text-warning"></i>
                                        </div>
                                    </div>
                                    <div class="media-body">

                                        There are many variations of passages of Lorem Ipsum available.
                                        <br>
                                        <small class="text-muted">Today 4:21 pm</small>
                                    </div>
                                </a>
                            </div>
                         
                        </div>

                    </div>

                    <div id="tab-2" class="tab-pane">

                        <div class="sidebar-title">
                            <h3> <i class="fa fa-cube"></i> Latest projects</h3>
                            <small><i class="fa fa-tim"></i> You have 14 projects. 10 not completed.</small>
                        </div>

                        <ul class="sidebar-list">
                            <li>
                                <a href="#">
                                    <div class="small pull-right m-t-xs">9 hours ago</div>
                                    <h4>Business valuation</h4>
                                    It is a long established fact that a reader will be distracted.

                                    <div class="small">Completion with: 22%</div>
                                    <div class="progress progress-mini">
                                        <div style="width: 22%;" class="progress-bar progress-bar-warning"></div>
                                    </div>
                                    <div class="small text-muted m-t-xs">Project end: 4:00 pm - 12.06.2014</div>
                                </a>
                            </li>

                        </ul>

                    </div>

                    <div id="tab-3" class="tab-pane">

                        <div class="sidebar-title">
                            <h3><i class="fa fa-gears"></i> Settings</h3>
                            <small><i class="fa fa-tim"></i> You have 14 projects. 10 not completed.</small>
                        </div>

                        <div class="setings-item">
                    <span>
                        Show notifications
                    </span>
                            <div class="switch">
                                <div class="onoffswitch">
                                    <input type="checkbox" name="collapsemenu" class="onoffswitch-checkbox" id="example">
                                    <label class="onoffswitch-label" for="example">
                                        <span class="onoffswitch-inner"></span>
                                        <span class="onoffswitch-switch"></span>
                                    </label>
                                </div>
                            </div>
                        </div>
                        <div class="setings-item">


                        <div class="sidebar-content">
                            <h4>Settings</h4>
                            <div class="small">
                                I belive that. Lorem Ipsum is simply dummy text of the printing and typesetting industry.
                                And typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.
                                Over the years, sometimes by accident, sometimes on purpose (injected humour and the like).
                            </div>
                        </div>

                    </div>
                </div>

            </div>
            </div>
            </div>
{% endblock %}
    </div>  
</div>
</body>
</html>