blog/blogadmin/urls.py
from django.conf.urls import url,include
from blogadmin.views import adminIndex,NewAccounts


urlpatterns = [
	url(r'^index/',adminIndex),
	url(r'^users/',NewAccounts,name="NewAccounts"),
]

blog/blogauth/urls.py
# encoding=utf8
from django.conf.urls import url,include
from django.contrib.auth.views import login,logout,password_change_done
from blogauth.views import userRegister,password_change

urlpatterns = [
    url(r'^login/$', login,{'template_name': 'registration/login.html'},name='login'),
    url(r'^logout/$', logout,{'template_name': 'registration/login.html'},name='logout'),
    url(r'^password_change/$', password_change,{'template_name': 'registration/password_change.html','post_change_redirect': '/accounts/login/'}, name='password_change'),  ##
    #不加{'post_change_redirect': 'done/'}会报NoReverseMatch Error（reverse(password_change_done)),原因未知
    url(r'^password_change/done/$', password_change_done, name='password_change_done'),
	url(r'^register/$',userRegister,name="userRegister"),
]

blog/blogdjango/urls.py
from django.conf.urls import url,include
from blogdjango import views
from django.contrib.auth.views import login
urlpatterns = [
	url(r'^index/$',views.selfIndex,name="selfIndex"),
	url(r'^test/$',views.test),
	url(r'^comment/$',views.Comment),
	url(r'^user/(?P<username>[a-zA-Z0-9]+)/$',views.userIndex),
	url(r'^user/(?P<username>[a-zA-Z0-9]+)/permission/',views.askPermission),
	url(r'^article/$',views.addNewActicle,name="addNewActicle"),
	url(r'^shortArticle/$',views.shortArticle,name="shortArticle"),
	url(r'^permission/$',views.processPermission,name="processPermission"),
	url(r'^userProfile/$',views.userProfile,name="userProfile"),
	url(r'^photo/$',views.photoView,name="photoView"),
	url(r'^uploadHeadPhoto/$',views.uploadHeadPhoto,name="uploadHeadPhoto"),
	url(r'^uploadArticlePhoto/$',views.uploadArticlePhoto,name="uploadArticlePhoto"),
]

blog/urls.py
from django.conf.urls import url,include



urlpatterns = [
	url(r'^accounts/',include("blogdjango.auth.urls",namespace="blogauth")),
	url(r'^blog/',include("blogdjango.blog.urls",namespace="blogdjango")),
	url(r'^admin/',include("blogdjango.admin.urls",namespace="blogadmin")),
]

blogdjango/blog/urls.py
from django.conf.urls import url,include
from blogdjango.blog import views
from django.contrib.auth.views import login
urlpatterns = [
	url(r'^friendDynamic/$',views.FriendDymic,name="FriendDymic"),
	url(r'^index/$',views.selfIndex,name="selfIndex"),
	url(r'^comment/$',views.Comment),
	url(r'^querycomment/$',views.userComment),
	url(r'^shortcomment/$',views.shortComment),
	url(r'^user/(?P<username>[a-zA-Z0-9]+)/$',views.userIndex),
	url(r'^user/(?P<username>[a-zA-Z0-9]+)/article/$',views.userActicle),
	url(r'^user/(?P<username>[a-zA-Z0-9]+)/shortArticle/$',views.userShortArticle),
	url(r'^user/(?P<username>[a-zA-Z0-9]+)/photo/$',views.userPhotoView),
	url(r'^user/(?P<username>[a-zA-Z0-9]+)/permission/',views.askPermission),
	url(r'^article/$',views.addNewActicle,name="addNewActicle"),
	url(r'^shortArticle/$',views.shortArticle,name="shortArticle"),
	url(r'^permission/$',views.processPermission,name="processPermission"),
	url(r'^permissioncontrol/$',views.processBlogPermission,name="processBlogPermission"),
	url(r'^userProfile/$',views.userProfile,name="userProfile"),
	url(r'^photo/$',views.photoView,name="photoView"),
	url(r'^uploadHeadPhoto/$',views.uploadHeadPhoto,name="uploadHeadPhoto"),
	url(r'^uploadArticlePhoto/$',views.uploadArticlePhoto,name="uploadArticlePhoto"),
	#url(r'^test/$',views.test),
]

blogdjango/models.py
# encoding=utf8
from django.db import models
from django.contrib.auth.models import User
import json 

class UserDetail(models.Model):
	user = models.OneToOneField(User)
	username = models.CharField(max_length=150,unique=True)
	nickname = models.CharField(max_length=200,default="",verbose_name=u"昵称")
	create_time = models.DateTimeField(auto_now_add=True,verbose_name=u"创建时间")
	access_confirm = models.BooleanField(default=True,verbose_name=u"访问权限控制")
	friends = models.ManyToManyField("self",through="Friends",symmetrical=False,related_name="Permission")
	contact_user = models.ManyToManyField("self",through="Message",symmetrical=False,related_name="Contact")  ###对称关系的话，through表会怎么表示
	signature = models.CharField(max_length=400,default="",verbose_name=u"个性签名")
	head_photo = models.ImageField(upload_to="face/%Y/%m/%d",null=True)
	blog_title = models.CharField(max_length=200,default="",verbose_name=u"blog名称")
	
	def __unicode__(self):
		return self.user.username  
	def getheadphotourl(self):
		try:
			return "/" + self.head_photo.url
		except ValueError:
			return "/face/default.jpg"

	class Meta:
		db_table = "user_detail"
		verbose_name = "用户详细数据"
		ordering = ["create_time"]



class Friends(models.Model):
	blog_priority = models.BooleanField(default=False,verbose_name="权限")
	ask_from_user = models.ForeignKey(UserDetail,related_name="asking_user")
	asked_user = models.ForeignKey(UserDetail,related_name="asked_user")
	ask_time = models.DateTimeField(auto_now_add=True,verbose_name=u"请求好友时间")
	need_confirm = models.BooleanField(default=True,verbose_name=u"需要审核")


	class Meta:
		db_table = "blog_friends"
		verbose_name = "博客权限"
		ordering = ["ask_time"]
		

class BlogText(models.Model):
	id = models.AutoField(primary_key=True)
	userDetail = models.ForeignKey(UserDetail)
	article_tags = models.CharField(max_length=400,default="",verbose_name=u"blogText tag")
	create_time = models.DateTimeField(auto_now_add=True,verbose_name=u"文档创建日期")
	context = models.TextField(verbose_name=u"blogText内容")
	blog_text_title = models.CharField(max_length=400,default="",verbose_name=u"blogText名称")
	is_publish = models.BooleanField(default=False,verbose_name=u"是否可以展示")

	def __unicode__(self):
		return self.blog_text_title  
	class Meta:
		db_table = "blog_text"
		verbose_name = "博客文档"
		ordering = ["-create_time"]

	def gettags(self):
		return self.article_tags.split(",")
		
class ShortArticle(models.Model):
	id = models.AutoField(primary_key=True)
	userDetail = models.ForeignKey(UserDetail)
	create_time = models.DateTimeField(auto_now_add=True,verbose_name=u"文档创建日期")
	context = models.TextField(verbose_name=u"内容")
	short_text_title = models.CharField(max_length=400,default="",verbose_name=u"名称")
	def __unicode__(self):
		return self.short_text_title  
	class Meta:
		db_table = "short_article"
		verbose_name = "短博文"
		ordering = ["-create_time"]
		
class Comment(models.Model):
	id = models.AutoField(primary_key=True)
	blogtext = models.ForeignKey(BlogText)
	parent_comment = models.ForeignKey("self",blank=True,null=True,related_name="children_comments")
	context = models.TextField()
	comment_user = models.ForeignKey(UserDetail,blank=True,null=True,on_delete=models.SET_NULL,related_name="comment_from")
	comment_to_user = models.ForeignKey(UserDetail,blank=True,null=True,on_delete=models.SET_NULL,related_name="comment_to")
	comment_time = models.DateTimeField(auto_now_add=True,verbose_name=u"评论时间")
	
	class Meta:
		db_table = "blog_comment"
		verbose_name = "博客评论"
		ordering = ["comment_time"]
		
class ShortComment(models.Model):
	id = models.AutoField(primary_key=True)
	shortarticle = models.ForeignKey(ShortArticle)
	parent_comment = models.ForeignKey("self",blank=True,null=True,related_name="children_comments")
	context = models.TextField()
	comment_user = models.ForeignKey(UserDetail,blank=True,null=True,on_delete=models.SET_NULL,related_name="short_comment_from")
	comment_to_user = models.ForeignKey(UserDetail,blank=True,null=True,on_delete=models.SET_NULL,related_name="short_comment_to")
	comment_time = models.DateTimeField(auto_now_add=True,verbose_name=u"评论时间")
	

	class Meta:
		db_table = "short_comment"
		verbose_name = "短博文评论"
		ordering = ["comment_time"]
		
class Message(models.Model):
	message = models.CharField(max_length=200,default="",verbose_name=u"聊天消息")
	contact_time = models.DateTimeField(auto_now_add=True,verbose_name=u"聊天时间")
	from_user = models.ForeignKey(UserDetail,related_name="sended_message")
	to_user = models.ForeignKey(UserDetail,related_name="recived_message")
	is_read = models.BooleanField(default=False,verbose_name=u"是否已读")
	
	class Meta:
		db_table = "blog_message"
		verbose_name = "聊天记录"
		ordering = ["-contact_time"]

class BlogPhoto(models.Model):
	id = models.AutoField(primary_key=True)
	userDetail = models.ForeignKey(UserDetail)
	upload_time = models.DateTimeField(auto_now_add=True,verbose_name=u"照片上传时间")
	photo = models.ImageField(upload_to="userphoto/%Y/%m/%d")

	def getphotourl(self):
		return "/" + self.photo.url
	class Meta:
		db_table = "blog_photo"
		verbose_name = "照片"
		ordering = ["-upload_time"]


		

blog/blogadmin/views.py
from django.shortcuts import render
from blogauth.decorators import account_admin_required
from django.template.response import TemplateResponse
from blogadmin.adminAction import adminAction
from django.http import HttpResponse
import json
# Create your views here.

@account_admin_required()
def adminIndex(request):
	username = request.user.username.split('@')[0]
	return TemplateResponse(request,"admin/base.html",{})
	
@account_admin_required()
def NewAccounts(request):
	mAdminAction = adminAction()
	if request.method == 'POST':
		context = mAdminAction.processConfirmAsk(request.POST)
		print context
		return HttpResponse(json.dumps(context),content_type="application/json")
	else:
		context = mAdminAction.queryNeedConfirmAccounts()
		return TemplateResponse(request,"admin/usermanage.html",context)

blog/blogdjango/views.py
# encoding=utf8
from django.shortcuts import render
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from blogdjango.auth.decorators import account_active_required
from blogdjango.models import UserDetail
from blogdjango.blogAction import BlogAction
from django.views.decorators.csrf import csrf_protect
from django.template.response import TemplateResponse
from django.core.exceptions import PermissionDenied
import json

# Create your views here.



@account_active_required()
def selfIndex(request):
	mblogAction = BlogAction(request.user)
	context = mblogAction.queryIndexData()
	return TemplateResponse(request,"blog/index.html",context)

@account_active_required()
def userIndex(request,username):
	mblogAction = BlogAction(request.user)
	context = mblogAction.queryIndexData(username)
	if context.has_key("denied"):
		return TemplateResponse(request,context["denied"],context)
	return TemplateResponse(request,"blog/index.html",context)

@csrf_protect
@account_active_required()
def Comment(request):
	mblogAction = BlogAction(request.user)
	if request.method == 'GET':
		context = mblogAction.queryActicleComment(request.GET)
	else:
		context = mblogAction.addNewComment(request.POST)
	if context.has_key("denied"):
		return TemplateResponse(request,context["denied"],context)
	return HttpResponse(json.dumps(context),content_type="application/json",status = context["code"])

@account_active_required()	
def askPermission(request,username):
	mblogAction = BlogAction(request.user)
	context = mblogAction.askBlogPermission(username)
	return HttpResponse(json.dumps(context),content_type="application/json",status = context["code"])

@csrf_protect
@account_active_required()
def processPermission(request):
	mblogAction = BlogAction(request.user)
	if request.method == 'GET':
		context = mblogAction.queryAskedPermission()
	else:
		context = mblogAction.processAskedPermission(request.POST)
		return HttpResponse(json.dumps(context),content_type="application/json",status = context["code"])
	return TemplateResponse(request,"blog/Permission.html",context,status = context["code"])

@csrf_protect
@account_active_required()
def addNewActicle(request):
	mblogAction = BlogAction(request.user)
	if request.method == 'POST':
		context = mblogAction.updateOrCreateArticle(request.POST)
		return HttpResponse(json.dumps(context),content_type="application/json",status = context["code"])
	else:
		context = mblogAction.queryArticle(tag=request.GET.get("tag-search",""))
		return TemplateResponse(request,"blog/ArticleEditor.html",context,status = context["code"])
		
@account_active_required()
def shortArticle(request):
	mblogAction = BlogAction(request.user)
	if request.method == 'POST':
		context = mblogAction.addNewShortArticle(request.POST)
		return HttpResponse(json.dumps(context),content_type="application/json",status = context["code"])
	else:
		context = mblogAction.queryShortArticle()
		return TemplateResponse(request,"blog/shortArticleEditor.html",context,status = context["code"])
		
def test(request):
	return TemplateResponse(request,"blog/test.html")

@account_active_required()
def userProfile(request):
	return TemplateResponse(request,"blog/userProfile.html",{})

@csrf_protect
@account_active_required()
def uploadHeadPhoto(request):
	if request.method == 'POST':
		mblogAction = BlogAction(request.user)
		context = mblogAction.uploadHeadPhoto(request.POST)
	else:
		context["code"] = 405
	return HttpResponse(json.dumps(context),content_type="application/json",status = context["code"])

@csrf_protect
@account_active_required()	
def photoView(request):
	mblogAction = BlogAction(request.user)
	if request.method == 'POST':
		context = mblogAction.uploadPhoto(request)
		return HttpResponse(json.dumps(context),content_type="application/json",status = context["code"])
	else:
		context = mblogAction.requeryPhoto()
	return TemplateResponse(request,"blog/photo.html",context,status = context["code"])


@csrf_protect
@account_active_required()
def uploadArticlePhoto(request):
	if request.method == 'POST':
		mblogAction = BlogAction(request.user)
		context = mblogAction.uploadArticlePhoto(request)
	else:
		context["code"] = 405
	return HttpResponse(json.dumps(context),content_type="application/json",status = context["code"]) 

blogdjango/admin/views.py
from django.shortcuts import render
from blogdjango.auth.decorators import account_admin_required
from django.template.response import TemplateResponse
from blogdjango.admin.adminAction import adminAction
from django.http import HttpResponse
import json
# Create your views here.
 
@account_admin_required()
def adminIndex(request):
	username = request.user.username.split('@')[0]
	return TemplateResponse(request,"admin/base.html",{})
	
@account_admin_required()
def NewAccounts(request):
	mAdminAction = adminAction()
	if request.method == 'POST':
		context = mAdminAction.processConfirmAsk(request.POST)
		return HttpResponse(json.dumps(context),content_type="application/json")
	else:
		context = mAdminAction.queryNeedConfirmAccounts()
		return TemplateResponse(request,"admin/usermanage.html",context)

blogdjango/templates/blog/Permission.html
{% extends 'blog/base_menu.html' %}
{% load static %}
{% block jshead %}
{{ block.super  }}
<script>
$(document).ready(function(){	
	$("#blogPermissionSwitch").change(function(){
		var checked =$(this).is(':checked');
		var json = {
			"permission" : checked
		}
		function commitSuccess(data,textStatus)
		{
			if(data)
			{
				Message("success","成功提交");
			}   
		}
		function commitError(XMLHttpRequest, textStatus, errorThrown)
		{
			if (XMLHttpRequest.status == 500) {
				Message("error","哎呀，服务器出错了");
			} 
		}
		commitJson(commitSuccess,commitError,json,"{% url 'blogdjango:processBlogPermission' %}","POST");
	});
	
});

</script>
{% endblock %}
{% block menulist %}
{% if not username %}
	<li id="li-1" class="menu-li">
		<a href="{% url 'blogdjango:FriendDymic' %}"><i class="fa fa-users"></i> <span class="nav-label">好友动态</span><span class="fa arrow"></span></a>
	</li>
{% endif %}
	<li id="li-2" class="menu-li">
		{% if username %}
		<a href="/blog/user/{{username}}/"><i class="fa fa-home"></i> <span class="nav-label">首页</span> <span class="fa arrow"></span></a>
		{% else %}
		<a href="{% url 'blogdjango:selfIndex' %}"><i class="fa fa-home"></i> <span class="nav-label">首页</span> <span class="fa arrow"></span></a>
		{% endif %}
	</li>
	<li id="li-3" class="menu-li">
		{% if username %}
		<a href="/blog/user/{{username}}/shortArticle/"><i class="fa fa-comment"></i> <span class="nav-label">调侃</span> <span class="fa arrow"></span></a>
		{% else %}
		<a href="{% url 'blogdjango:shortArticle' %}"><i class="fa fa-comment"></i> <span class="nav-label">调侃</span> <span class="fa arrow"></span></a>
		{% endif %}
	</li>
	<li id="li-4" class="menu-li">
		{% if username %}
		<a href="/blog/user/{{username}}/article/"><i class="fa fa-file-text-o"></i> <span class="nav-label">博客文章</span> <span class="fa arrow"></span></a>
		{% else %}
		<a href="{% url 'blogdjango:addNewActicle' %}"><i class="fa fa-file-text-o"></i> <span class="nav-label">博客文章</span> <span class="fa arrow"></span></a>
		{% endif %}
	</li>
	<li id="li-5" class="menu-li">
		{% if username %}
		<a href="/blog/user/{{username}}/photo/"><i class="fa fa-picture-o"></i> <span class="nav-label">照片</span> <span class="fa arrow"></span></a>
		{% else %}
		<a href="{% url 'blogdjango:photoView' %}"><i class="fa fa-picture-o"></i> <span class="nav-label">照片</span> <span class="fa arrow"></span></a>
		{% endif %}
	</li>
	{% if not username %}
	<li id="li-6" class="active menu-li">
		<a href="{% url 'blogdjango:processPermission' %}"><i class="fa fa-cog"></i> <span class="nav-label">博客设置</span><span class="fa arrow"></span></a>
		<ul class="nav nav-second-level collapse">
			<li><a href="{% url 'blogdjango:processPermission' %}">权限管理</a></li>
			<li><a href="{% url 'blogdjango:userProfile' %}">用户配置</a></li>
		</ul>
	</li>
	{% endif %}
{% endblock %}
{% block content %}
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>Blog</h2>
        <ol class="breadcrumb">
            <li>
                <a href="#">Blog</a>
            </li>

            <li class="active">
                <strong>permission</strong>
            </li>
        </ol>
    </div>
    <div class="col-lg-2">

    </div>
</div>
        <div class="row">
            <div class="col-lg-12">
                <div class="ibox float-e-margins">
                    <div class="ibox-title  back-change">
                        <h5>blog权限设置</h5>
                        <div class="ibox-tools">
                            <a class="collapse-link">
                                <i class="fa fa-chevron-up"></i>
                            </a>
                            <a class="close-link">
                                <i class="fa fa-times"></i>
                            </a>
                        </div>
                    </div>
                    <div class="ibox-content">
					<form class="form-horizontal" role="form">
						<div class="form-group">
						 <label class="control-label" for="name">开启blog的权限控制</label>
                  
							<div class="onoffswitch">
							{% if userDetail.access_confirm %}
								<input type="checkbox" class="onoffswitch-checkbox" id="blogPermissionSwitch" checked="checked">
								{% else %}
								<input type="checkbox" class="onoffswitch-checkbox" id="blogPermissionSwitch">
								{% endif %}
								<label class="onoffswitch-label" for="blogPermissionSwitch">
									<span class="onoffswitch-inner"></span>
									<span class="onoffswitch-switch"></span>
								</label>
							</div>
						</div>
					</form>
                    </div>
                </div>
            </div>
        </div>

<div class="row">
    <div class="col-lg-12">
        <div class="wrapper wrapper-content animated fadeInUp">

            <div class="ibox">
                    <div class="ibox-title  back-change">
                        <h5>新的好友申请</h5>
                        <div class="ibox-tools">
                            <a class="collapse-link">
                                <i class="fa fa-chevron-up"></i>
                            </a>
                            <a class="close-link">
                                <i class="fa fa-times"></i>
                            </a>
                        </div>
                    </div>
                <div class="ibox-content">
                        <table class="table table-hover">
                            <tbody>
                            <tr>
                                    <th>用户名</th>
                                    <th>申请时间</th>
                                    <th>是否同意</th>
                            </tr>
                            {% for permission in permissons %}
                            <tr>
                                <td class="project-title">
                                    <a href="#">{{permission.ask_from_user.user.username}}</a>
                                </td>
                                 <td class="project-title">
                                    <small>{{permission.ask_time}}</small>
                                </td>
                                <td class="project-actions">
									<div class="switch">
										<div class="onoffswitch">
											<input type="checkbox" class="onoffswitch-checkbox" id="{{permission.ask_from_user.user.username}}" value="{{permission.ask_from_user.user.username}}" name="friendActivecheckbox">
											<label class="onoffswitch-label" for="{{permission.ask_from_user.user.username}}">
												<span class="onoffswitch-inner"></span>
												<span class="onoffswitch-switch"></span>
											</label>
										</div>
									</div>
                                </td>                                
                            </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                <div class="text-center">
                        <a data-toggle="modal" class="btn btn-primary" href="#" id="blogPermissionSubmit" onclick="friendActive()">提交</a>
                </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

blogdjango/templates/blog/base.html
<!DOCTYPE html>
<html>

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <title>BLOG</title>
    {% load static %}
    {% block jshead %}
	<link href="http://libs.baidu.com/bootstrap/3.0.3/css/bootstrap.min.css" rel="stylesheet">
    <link href="http://libs.baidu.com/fontawesome/4.0.3/css/font-awesome.min.css" rel="stylesheet">
	<link href="http://cdn.bootcss.com/metisMenu/2.5.2/metisMenu.min.css" rel="stylesheet">
	<link href="http://cdn.bootcss.com/toastr.js/latest/css/toastr.min.css" rel="stylesheet">
    <!--<link href="http://libs.cdnjs.net/files/ladda.bootstrap/0.1/ladda.min.css" rel="stylesheet"></script>-->
	<!-- <link href="http://libs.cdnjs.net/files/jquery.gritter/1.7.4/css/jquery.gritter.css" rel="stylesheet"> -->
    <link href="{% static 'admin/css/animate.css' %}" rel="stylesheet">
    <link href="{% static 'admin/css/style.css' %}" rel="stylesheet">
	
   
	<script src="http://apps.bdimg.com/libs/jquery/2.1.4/jquery.min.js"></script>
	<script src="http://libs.baidu.com/bootstrap/3.0.3/js/bootstrap.min.js"></script>
    <script src="http://cdn.bootcss.com/metisMenu/2.5.2/metisMenu.min.js"></script>
	<script src="http://cdn.bootcss.com/jQuery-slimScroll/1.3.7/jquery.slimscroll.min.js"></script>
    
	

    <script src="http://cdn.bootcss.com/pace/1.0.2/pace.min.js"></script> 
	<!-- <script src="http://libs.cdnjs.net/files/jquery.ui/1.11.4/jquery-ui.min.js"></script>  跟summernote冲突 -->
    <!-- <script src="http://libs.cdnjs.net/files/jquery.gritter/1.7.4/js/jquery.gritter.min.js"></script> -->
	<script src="http://apps.bdimg.com/libs/jquery.cookie/1.4.1/jquery.cookie.js"></script>

    <script src="http://cdn.bootcss.com/toastr.js/latest/js/toastr.min.js"></script>
	<!-- <script src="http://libs.cdnjs.net/files/ladda.bootstrap/0.1/spin.min.js"></script>-->
	<!-- <script src="http://libs.cdnjs.net/files/ladda.bootstrap/0.1/ladda.min.js"></script> -->
    <script src="{% static 'blog/js/xianyouq.js' %}"></script>
    <script src="{% static 'admin/js/inspinia.js' %}"></script>
    {% endblock %}
</head>

<body class="navbar"> <!--mini-fixed-sidebar 菜单固定 fixed-nav fixed-nav-basic nav固定 -->
    <div id="wrapper ">
       {% block leftmenu %}
       <!-- style.css 有针对 id="page-wrapper"特殊设置,所以把下面这个包括在block里面  -->
        <div class="gray-bg dashbard-1">
        {% endblock %}
        <div class="row border-bottom">
        <nav class="navbar navbar-static-top " role="navigation" style="margin-bottom: 0"> <!-- navbar-fixed-top 固定nav navbar-static-top  不固定nav -->
            {% block navhead %}
            <!-导航头-->
            {% endblock %}
        </nav>
        </div>
	{% block content %}
	{% endblock %}
    {% block chatbox %}
    {% endblock %}
    {% block rightsidebar %}
    {% endblock %}
    </div>  
</div>
</body>
</html>